### ISSUE TITLE
Lack of Map

### ISSUE THREAD

**Issue by aaronjs99** [richardw05/mybot_ws#3]
**run_nav.sh** leads to **acml_demo.launch** where there is a line referring to a test map in the package: `"$(find mybot_navigation)/maps/test_map.yaml"`. However there seems to be no **maps** folder in **mybot_navigation**, not to mention **maps/test_map.yaml**
Please look into this

**Comment by pedramsafaei** [comment]
This is due to the fact that you'd have to create the map, save it and then load it. You can see the steps in detail here  http://www.moorerobots.com/blog/post/3

tldr; 

```
roslaunch mybot_gazebo mybot_world.launch
roslaunch mybot_navigation gmapping_demo.launch
roslaunch mybot_description mybot_rviz_gmapping.launch
roslaunch mybot_navigation mybot_teleop.launch
rosrun map_server map_saver -f ~/mybot_ws/src/mybot_navigation/maps/test_map
```

Close all previous terminals 

```
roslaunch mybot_gazebo mybot_world.launch
roslaunch mybot_navigation amcl_demo.launch
roslaunch mybot_description mybot_rviz_amcl.launch
```
